import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's GitHub repository.
*/
`;

const prod = process.argv[2] === "production";

// Build the embedding iframe as a SEPARATE browser bundle so @huggingface/
// transformers (heavy, browser-only) never enters main.js. The result is inlined
// into the main build via the `__IFRAME_CONTENTS_PLACEHOLDER__` define (ADR-109 M2).
const iframeBuild = await esbuild.build({
  entryPoints: ["services/embedding/host/frame/bootstrap.ts"],
  bundle: true,
  platform: "browser",
  format: "esm",
  target: "esnext",
  write: false,
  minify: prod,
  logLevel: "info",
});
const iframeHtml = `<script type="module">\n${iframeBuild.outputFiles[0].text}\n</script>\n`;

// Build the embedding Web Worker as its own browser bundle (ADR-119) — same runtime
// as the iframe but run on a background thread. Inlined as a plain-source string via
// `__WORKER_CONTENTS_PLACEHOLDER__`; WorkerEmbeddingProvider wraps it in a Blob URL.
const workerBuild = await esbuild.build({
  entryPoints: ["services/embedding/host/frame/worker.ts"],
  bundle: true,
  platform: "browser",
  format: "esm",
  target: "esnext",
  write: false,
  minify: prod,
  logLevel: "info",
});
const workerSource = workerBuild.outputFiles[0].text;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  define: {
    __IFRAME_CONTENTS_PLACEHOLDER__: JSON.stringify(iframeHtml),
    __WORKER_CONTENTS_PLACEHOLDER__: JSON.stringify(workerSource),
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
