import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's GitHub repository.
*/
`;

const prod = process.argv[2] === "production";

// Build the embedding backend as ONE SEPARATE browser bundle so @huggingface/
// transformers (heavy, browser-only) never enters main.js. The SAME bundle runs
// as both the Web Worker (off-thread) and the iframe fallback — it detects its
// context at runtime (frame/entry.ts, ADR-121) — so the ML runtime is inlined
// ONCE via the `__EMBEDDING_BUNDLE_PLACEHOLDER__` define (referenced once, in
// embeddingBundle.ts), instead of twice.
const embeddingBuild = await esbuild.build({
  entryPoints: ["services/embedding/host/frame/entry.ts"],
  bundle: true,
  platform: "browser",
  format: "esm",
  target: "esnext",
  write: false,
  minify: prod,
  logLevel: "info",
});
const embeddingSource = embeddingBuild.outputFiles[0].text;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  define: {
    __EMBEDDING_BUNDLE_PLACEHOLDER__: JSON.stringify(embeddingSource),
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
