import { describe, it, expect } from "vitest";
import {
	parseGlossary,
	normalizeTerm,
	buildTermIndex,
	canonicalTerm,
	type GlossaryEntry,
} from "../services/glossary";

const entry = (over: Partial<GlossaryEntry> = {}): GlossaryEntry => ({
	term: "Sparse Coding",
	definition: "A representation where few neurons are active at once.",
	source: "model",
	updatedAt: "2026-09-15T00:00:00.000Z",
	...over,
});

/**
 * A glossary entry exactly as builds up to 2.13.x wrote it — provenance in the
 * `%% pythia: … %%` comment, card fields as visible labels (ADR-149).
 *
 * A literal rather than a re-implemented renderer: this file's job now is to
 * prove the migration can still read what those builds produced, and a fixture
 * generated by our own code could drift with it and still pass.
 */
const LEGACY_2_13 = [
	"## Zähler",
	"%% pythia: source=model updatedAt=2026-09-15T00:00:00.000Z model=gpt-5-mini %%",
	"",
	"Ein Gerät, das diskrete Ereignisse erfasst.",
	"",
	"**Forms:** Zählers · Zählern · sparse counter",
	"**Translations:** en: counter · it: contatore",
	"**Context:** Der Zähler wird monatlich abgelesen.",
	"",
].join("\n");

describe("normalizeTerm", () => {
	it("folds case and collapses whitespace so lookups are stable", () => {
		expect(normalizeTerm("  Sparse   CODING ")).toBe("sparse coding");
	});
});

describe("parseGlossary", () => {
	it("reads terms, definitions and provenance", () => {
		const md = `# Glossary\n\n## Sparse Coding\n%% pythia: source=model updatedAt=2026-09-15T00:00:00.000Z %%\n\nFew neurons active.\n`;
		const [e] = parseGlossary(md);
		expect(e.term).toBe("Sparse Coding");
		expect(e.definition).toBe("Few neurons active.");
		expect(e.source).toBe("model");
		expect(e.updatedAt).toBe("2026-09-15T00:00:00.000Z");
	});

	it("treats a hand-written entry with no marker as manual", () => {
		const [e] = parseGlossary("## Landauer\n\nA thermodynamic bound.\n");
		expect(e.source).toBe("manual");
		expect(e.updatedAt).toBeUndefined();
	});

	it("keeps multi-paragraph definitions intact", () => {
		const [e] = parseGlossary("## Term\n\nFirst para.\n\nSecond para.\n");
		expect(e.definition).toBe("First para.\n\nSecond para.");
	});

	it("ignores a preamble above the first heading", () => {
		const md = "---\ntags: glossary\n---\n\n# My Glossary\nSome intro.\n\n## Term\n\nDef.\n";
		expect(parseGlossary(md).map((e) => e.term)).toEqual(["Term"]);
	});

	it("keeps a heading with no body rather than dropping it", () => {
		// Losing a hand-written entry to a strict parser is worse than an odd one.
		const entries = parseGlossary("## Empty\n\n## Full\n\nDef.\n");
		expect(entries.map((e) => e.term)).toEqual(["Empty", "Full"]);
		expect(entries[0].definition).toBe("");
	});

	it("returns nothing for an empty or heading-less note", () => {
		expect(parseGlossary("")).toEqual([]);
		expect(parseGlossary("just prose, no headings")).toEqual([]);
	});
});

describe("buildTermIndex", () => {
	const matches = (re: RegExp, text: string) => text.match(re) ?? [];
	/** Index a list of bare terms — the alias-free case most of these cover. */
	const matcherFor = (terms: string[]) => buildTermIndex(terms.map((term) => ({ term })))?.matcher ?? null;

	it("returns null for an empty glossary so the painter can skip the walk", () => {
		expect(matcherFor([])).toBeNull();
		expect(matcherFor(["a"])).toBeNull(); // single characters match far too much
	});

	it("matches a term case-insensitively, every occurrence", () => {
		const re = matcherFor(["Neuron"])!;
		expect(matches(re, "A neuron and another Neuron.")).toEqual(["neuron", "Neuron"]);
	});

	it("prefers the longest term when two overlap", () => {
		// First-match alternation would return "Coding"; sorting by length fixes it.
		const re = matcherFor(["Coding", "Sparse Coding"])!;
		expect(matches(re, "See Sparse Coding here.")).toEqual(["Sparse Coding"]);
	});

	it("does not match inside a longer word", () => {
		const re = matcherFor(["Ion"])!;
		expect(matches(re, "Ionisation and Nation")).toEqual([]);
	});

	it("bounds non-ASCII terms correctly, where \\b would fail", () => {
		const re = matcherFor(["Zähler"])!;
		expect(matches(re, "Der Zähler ist undefiniert.")).toEqual(["Zähler"]);
		expect(matches(re, "Zählerstand")).toEqual([]);
	});

	it("treats a term with regex metacharacters literally", () => {
		const re = matcherFor(["C++"])!;
		expect(matches(re, "written in C++ here")).toEqual(["C++"]);
	});

	it("de-duplicates terms differing only by case or spacing", () => {
		const re = matcherFor(["Neuron", "neuron", " NEURON "])!;
		expect(matches(re, "neuron")).toEqual(["neuron"]);
	});
});

describe("aliases", () => {
	it("reads forms written as a visible field, spaces and all", () => {
		const md = LEGACY_2_13;
		const [e] = parseGlossary(md);
		expect(e.aliases).toEqual(["Zählers", "Zählern", "sparse counter"]);
		expect(e.updatedAt).toBe("2026-09-15T00:00:00.000Z");
		expect(e.source).toBe("model");
	});

	it("leaves aliases undefined when the entry has no forms field", () => {
		expect(parseGlossary("## Alpha\n\nDef.\n")[0].aliases).toBeUndefined();
	});

	it("matches an alias and resolves it back to the canonical term", () => {
		const ix = buildTermIndex([entry({ term: "Zähler", aliases: ["Zählern", "counter"] })])!;
		expect("Mit den Zählern und dem counter".match(ix.matcher)).toEqual(["Zählern", "counter"]);
		expect(canonicalTerm(ix, "Zählern")).toBe("Zähler");
		expect(canonicalTerm(ix, "COUNTER")).toBe("Zähler");
	});

	it("never lets one entry's alias shadow another entry's own term", () => {
		// "Zähler" is entry two's term but entry one lists it as an alias. Order in
		// the note must not decide which definition the word opens.
		const ix = buildTermIndex([
			entry({ term: "Counter", aliases: ["Zähler"] }),
			entry({ term: "Zähler" }),
		])!;
		expect(canonicalTerm(ix, "Zähler")).toBe("Zähler");
	});

	it("still prefers the longest surface form when an alias overlaps a term", () => {
		const ix = buildTermIndex([
			entry({ term: "Coding" }),
			entry({ term: "Sparse Representation", aliases: ["Sparse Coding"] }),
		])!;
		expect("See Sparse Coding here.".match(ix.matcher)).toEqual(["Sparse Coding"]);
		expect(canonicalTerm(ix, "Sparse Coding")).toBe("Sparse Representation");
	});

	it("drops aliases too short to be useful, like the terms themselves", () => {
		const ix = buildTermIndex([entry({ term: "Neuron", aliases: ["N"] })])!;
		expect("N and Neuron".match(ix.matcher)).toEqual(["Neuron"]);
	});
});

describe("model provenance (ADR-144)", () => {
	it("reads the model that wrote the definition", () => {
		const md = "## Alpha\n%% pythia: source=model updatedAt=2026-09-15T00:00:00.000Z model=claude-haiku-4-5 %%\n\nDef.\n";
		expect(parseGlossary(md)[0].model).toBe("claude-haiku-4-5");
	});

	it("stays absent for a hand-written entry", () => {
		const md = "## Alpha\n%% pythia: source=manual %%\n\nDef.\n";
		expect(parseGlossary(md)[0].model).toBeUndefined();
	});

	it("survives alongside forms", () => {
		const parsed = parseGlossary(LEGACY_2_13)[0];
		expect(parsed.model).toBe("gpt-5-mini");
		expect(parsed.aliases).toEqual(["Zählers", "Zählern", "sparse counter"]);
	});
});

// ── Reading the 2.13.x single-note format (migration source) ──────────────────

describe("legacy visible fields", () => {
	it("reads forms, translations and context out of the body", () => {
		const [e] = parseGlossary(LEGACY_2_13);
		expect(e.aliases).toEqual(["Zählers", "Zählern", "sparse counter"]);
		expect(e.translations).toEqual([
			{ lang: "en", term: "counter" },
			{ lang: "it", term: "contatore" },
		]);
		expect(e.contexts).toEqual(["Der Zähler wird monatlich abgelesen."]);
	});

	it("keeps the labelled lines out of the definition", () => {
		expect(parseGlossary(LEGACY_2_13)[0].definition).toBe("Ein Gerät, das diskrete Ereignisse erfasst.");
	});

	it("keeps labelled lines out of the definition", () => {
		const md = `## Zähler\n\nEin Gerät, das Ereignisse erfasst.\n\n**Forms:** Zählers\n**Context:** Der Zähler läuft.\n`;
		const [e] = parseGlossary(md);
		expect(e.definition).toBe("Ein Gerät, das Ereignisse erfasst.");
	});

	it("reads a hand-typed label without bold markers", () => {
		// The note is hand-edited, so someone will type the label plainly.
		const md = `## Zähler\n\nEin Gerät.\n\nForms: Zählers · Zählern\nTranslations: en: counter\n`;
		const [e] = parseGlossary(md);
		expect(e.aliases).toEqual(["Zählers", "Zählern"]);
		expect(e.translations).toEqual([{ lang: "en", term: "counter" }]);
	});

	it("accepts | and , as hand-edit separators alongside the written ·", () => {
		const md = `## Zähler\n\nEin Gerät.\n\n**Forms:** Zählers | Zählern\n`;
		expect(parseGlossary(md)[0].aliases).toEqual(["Zählers", "Zählern"]);
	});

	it("drops a translation with no language code rather than guessing one", () => {
		const md = `## Zähler\n\nEin Gerät.\n\n**Translations:** counter · it: contatore\n`;
		expect(parseGlossary(md)[0].translations).toEqual([{ lang: "it", term: "contatore" }]);
	});

	it("still reads aliases from the legacy comment marker", () => {
		// A glossary written before ADR-149 must keep marking its variants.
		const md = `## Zähler\n%% pythia: source=model aliases=Zählers|Zählern %%\n\nEin Gerät.\n`;
		expect(parseGlossary(md)[0].aliases).toEqual(["Zählers", "Zählern"]);
	});

	it("matches a translation and resolves it back to the canonical term", () => {
		// An Italian answer should mark "contatore" and open the German entry.
		const index = buildTermIndex([
			{ term: "Zähler", translations: [{ lang: "it", term: "contatore" }] },
		]);
		expect(index).not.toBeNull();
		expect("Il contatore è rotto.".match(index!.matcher)?.[0]).toBe("contatore");
		expect(canonicalTerm(index!, "contatore")).toBe("Zähler");
	});
});
